USE test;

DROP TABLE IF EXISTS PLANS;

CREATE TABLE PLANS (
  ID BIGINT(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
  HOTEL_ID BIGINT(11) NOT NULL COMMENT 'hotel Id',
  DESCRIPTION VARCHAR(1024) NULL,
  PLAN_START DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PLAN_END DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  IMAGE_URL VARCHAR(255) NULL,
  PRIMARY KEY (ID, HOTEL_ID)
);
INSERT INTO PLANS (HOTEL_ID, DESCRIPTION, PLAN_START, PLAN_END, IMAGE_URL) VALUES
  (1, 'Nice Plan','1998-12-31', '2018-12-31', 'http://imgurl.com'),
  (1, 'Better Plan','1988-12-31', '2018-12-31', 'http://imgurl.com')
;